### ISSUE TITLE
the gl viewport data is wrong

### ISSUE THREAD

**Issue by AmyOrz** [Wonder-Technology/Wonder-Editor#15]
# environment
## editor version
v0.10.0

## engine version
v1.0.0-alpha.18.5

# description
![image](https://user-images.githubusercontent.com/10692572/39624256-2afdd9bc-4fcb-11e8-9a54-76d18fc7b4cd.png)

as the above screenshot, edit engine canvas's actual size is 927.5 * 291.41, but the setted viewport data(set when exec init pipeline) is 1855 * 427(they should be the same!)

# reason
the setted viewport data is wrong

# solution
the setted viewport data is full screen data, but it should:
1.set viewport after react dom didmout
2.the setted viewport data should be the canvas css width,height

**Comment by yyc-git** [comment]
fixed
